language: ruby
rvm:
  - 2.4.1

notifications:
  email: false
  slack: bramvanosta:EzBQl2zZ3yXmFo5sVNBAP40H

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_script:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- cd client
- . $HOME/.nvm/nvm.sh
- nvm install node
- nvm use node
- npm install
- cd ../api
- bundle install
- RAILS_ENV=travis rails db:create
- RAILS_ENV=travis rails db:migrate

script:
- RAILS_ENV=travis bundle exec rspec
- cd ../client
- npm run test

before_deploy:
- cd ..
- openssl aes-256-cbc -K $encrypted_8091f3ac13c9_key -iv $encrypted_8091f3ac13c9_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
- provider: script
  script: ./scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: master
