sudo: required
dist: trusty

language: node_js
node_js:
  - '6.9'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta
    
notifications:
  slack: bramvanosta:EzBQl2zZ3yXmFo5sVNBAP40H

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - cd client
  - npm install -g @angular/cli
  - npm install -g karma
  - npm install
  - ng build

script: karma start --single-run
