sudo: required
dist: trusty
language: node_js

node_js:
  - '6.9'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

notifications:
  email: false
  slack: bramvanosta:EzBQl2zZ3yXmFo5sVNBAP40H

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - cd client
  - npm install

script:
  - npm run test

before_deploy:
- cd ..
- openssl aes-256-cbc -K $encrypted_8091f3ac13c9_key -iv $encrypted_8091f3ac13c9_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
- provider: script
  script: "./scripts/deploy.sh"
  skip_cleanup: true
  on:
    branch: master
