version: '2'

services:
  bs_api:
    container_name: bs_api
    build: ./api
    volumes:
      - ./api:/var/www/html/api

  bk_nginx:
    container_name: bs_nginx
    build: images/nginx/development
    volumes:
      - ./logs:/var/www/logs
    ports:
      - 80:80

  bs_api_db:
    container_name: bs_api_db
    image: postgres:alpine
    environment:
      - "POSTGRES_USER=user"
      - "POSTGRES_PASSWORD=password"

  bs_client:
    container_name: bs_client
    build: ./client
    working_dir: /var/www/html/client
    command: "sh -c 'yarn && npm start'"
    volumes:
      - ./client:/var/www/html/client
    ports:
      - 4200:4200
