version: '2.1'

services:
  bs_api:
    container_name: bs_api
    build: ./api
    volumes:
      - ./api:/var/www/html/api
    depends_on:
      bs_api_db:
        condition: service_healthy


  bk_nginx:
    container_name: bs_nginx
    build: images/nginx/development
    volumes:
      - ./logs:/var/www/logs
    ports:
      - 80:80
    depends_on:
      bs_api_db:
        condition: service_healthy


  bs_api_db:
    container_name: bs_api_db
    image: postgres:alpine
    environment:
      - "POSTGRES_USER=user"
      - "POSTGRES_PASSWORD=password"
    healthcheck:
      test: psql -U user -w --list
      interval: 2s
      timeout: 5s
      retries: 30

  bs_client:
    container_name: bs_client
    build: ./client
    working_dir: /var/www/html/client
    command: "sh -c 'yarn && npm start'"
    volumes:
      - ./client:/var/www/html/client
    ports:
      - 4200:4200
