default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: booking-system_development
  username: user
  password: password
  host: bs_api_db

test:
  <<: *default
  database: booking-system_test
  username: user
  password: password
  host: bs_api_db

test:
  <<: *default
  database: booking-system_travis
  username: travis
  password:
  host: 127.0.0.1

staging:
  <<: *default
  database: booking-system_staging
  username: bookingsystem
  password: bookingsystem
  host: localhost
  port: 5432

production:
  <<: *default
  database: booking-system_production
  username: app
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
