default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: booking-system_development
  username: user
  password: password
  host: bs_api_db

test:
  <<: *default
  database: app_test
  username: user
  password: password
  host: bs_api_db

production:
  <<: *default
  database: app_production
  username: app
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
