source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'rails', '~> 5.1.1'
gem 'pg', '~> 0.18'
gem 'puma', '~> 3.7'

gem 'rack-cors'

gem 'rack-attack'

gem 'active_model_serializers'

gem 'money-rails'

gem 'geocoder'

gem 'bcrypt'

gem 'devise'
gem 'devise_token_auth'
gem 'omniauth'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails', '~> 3.5'
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'

  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'

  gem 'annotate'

  gem 'faker'
end

group :test do
  gem 'factory_girl_rails', '~> 4.0'
end
